//app/layout.js
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  console.log("Clerk Publishable Key:", process.env.REACT_APP_CLERK_PUBLISHABLE_KEY);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
    
  )
}
